
import React, { useState } from 'react';
import { AlertTriangle, Send, Activity, Info, ShieldAlert } from 'lucide-react';
import { analyzeHealthSymptom } from '../services/geminiService';
import { ActivityLog } from '../types';

interface Props {
  activities: ActivityLog[];
}

const HealthMonitor: React.FC<Props> = ({ activities }) => {
  const [symptom, setSymptom] = useState('');
  const [analysis, setAnalysis] = useState('');
  const [loading, setLoading] = useState(false);

  const handleAnalysis = async () => {
    if (!symptom.trim()) return;
    setLoading(true);
    try {
      const summary = activities.length > 0 ? activities[0].type : "Low active";
      const result = await analyzeHealthSymptom(symptom, summary);
      setAnalysis(result);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <header className="text-center space-y-2">
        <div className="w-16 h-16 bg-red-50 text-red-500 rounded-3xl flex items-center justify-center mx-auto mb-4">
          <ShieldAlert size={32} />
        </div>
        <h2 className="text-3xl font-bold text-slate-800">AI Health Monitor</h2>
        <p className="text-slate-500">Log any unusual symptoms or bodily changes for instant AI analysis.</p>
      </header>

      <div className="bg-white p-8 rounded-[40px] border border-slate-100 shadow-xl shadow-slate-200/50">
        <div className="space-y-4">
          <label className="text-sm font-bold text-slate-700 ml-1">Describe what you are feeling:</label>
          <textarea 
            value={symptom}
            onChange={(e) => setSymptom(e.target.value)}
            placeholder="e.g., Shortness of breath during light jogging, unusual heart palpitations, or sudden fatigue..."
            className="w-full h-32 bg-slate-50 border-none rounded-3xl p-6 text-slate-800 focus:ring-2 focus:ring-red-500 resize-none transition-all placeholder:text-slate-400"
          ></textarea>
          <button 
            onClick={handleAnalysis}
            disabled={loading || !symptom}
            className="w-full bg-slate-900 text-white py-4 rounded-3xl font-bold flex items-center justify-center gap-2 hover:bg-black transition-all disabled:opacity-50"
          >
            {loading ? <div className="animate-spin rounded-full h-5 w-5 border-2 border-white/30 border-t-white" /> : <><Activity size={20} /> Analyze Health State</>}
          </button>
        </div>
      </div>

      {analysis && (
        <div className="bg-white p-8 rounded-[40px] border border-red-100 shadow-lg animate-in fade-in zoom-in duration-300">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-red-50 text-red-600 rounded-xl flex items-center justify-center">
              <Info size={20} />
            </div>
            <h3 className="text-xl font-bold text-slate-800">Analysis Result</h3>
          </div>
          <div className="prose prose-slate max-w-none text-slate-600 leading-relaxed">
            {analysis.split('\n').map((para, i) => (
              <p key={i} className="mb-4">{para}</p>
            ))}
          </div>
          <div className="mt-8 p-4 bg-yellow-50 border border-yellow-100 rounded-2xl flex gap-3 items-start">
            <AlertTriangle className="text-yellow-600 shrink-0 mt-1" size={18} />
            <p className="text-xs text-yellow-800 leading-tight">
              <strong>DISCLAIMER:</strong> This analysis is generated by AI and provided for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician.
            </p>
          </div>
        </div>
      )}

      {/* Suggested Activities */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-slate-900 p-8 rounded-[40px] text-white">
          <h4 className="text-xl font-bold mb-4">Wellness Tip</h4>
          <p className="text-slate-400 text-sm mb-6">Feeling sluggish? A 10-minute deep breathing exercise can significantly improve blood oxygenation and reduce cortisol.</p>
          <button className="bg-white/10 text-white px-6 py-2.5 rounded-full text-sm font-bold hover:bg-white/20 transition-all">Start Session</button>
        </div>
        <div className="bg-indigo-50 p-8 rounded-[40px] border border-indigo-100">
          <h4 className="text-xl font-bold text-indigo-900 mb-4">Activity Suggestion</h4>
          <p className="text-indigo-700/70 text-sm mb-6">Based on your logs, you haven't done much mobility work lately. Try 15 minutes of dynamic stretching.</p>
          <button className="bg-indigo-600 text-white px-6 py-2.5 rounded-full text-sm font-bold hover:bg-indigo-700 transition-all">View Tutorial</button>
        </div>
      </div>
    </div>
  );
};

export default HealthMonitor;
